### ISSUE TITLE
Styles for prod environment missing

### ISSUE THREAD

**Issue by Arekusei** [yiidoc/yii2-redactor#54]
In dev environment include `redactor.css`:

``` css
#redactor-modal-close {
  position: absolute;
  top: 10px;
  right: 10px;
  width: 30px;
  height: 30px;
  text-align: right;
  color: #bbb;
  font-size: 30px;
  font-weight: 300;
  cursor: pointer;
  -webkit-appearance: none;
  padding: 0;
  border: 0;
  background: 0;
  outline: none;
}
```

In prod environment include `redactor.min.css`:

``` css
#redactor-modal-close {
    position: absolute;
    top: 10px;
    right: 10px;
    width: 30px;
    height: 30px;
    text-align: right;
    color: #bbb;
    font-size: 30px;
    font-weight: 300;
    cursor: pointer;
}
```

This styles missing in `*.min.css` version:

``` css
#redactor-modal-close {
  /*....*/
  -webkit-appearance: none;
  padding: 0;
  border: 0;
  background: 0;
  outline: none;
}
```
